firstname = input("Enter your firstname:")
print("My firstname is",firstname)
lastname = input("enter your lastname:")
print("My lastname is",lastname)
age = int(input("Enter age :"))
print("I am",age,"years old")